name: Atualizar EPG

on:
  workflow_dispatch:

  schedule:
    - cron: "5 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install -r scripts/requirements.txt
          playwright install chromium

      - name: Gerar XMLTV
        run: |
          python scripts/build_epg.py

      - name: Comprimir XML
        run: |
          gzip -kf epg/mozambique.xml

      - name: Commit automático
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Atualização automática do EPG